require("mrx.core.keymaps")
require("mrx.core.options")
require("mrx.core.colorscheme")

-- Plugins
require("mrx.plugins.treesitter")
require("mrx.plugins.telescope")
require("mrx.plugins.webdevicons")
require("mrx.plugins.lualine")
require("mrx.plugins.gitsigns")
require("mrx.plugins.harpoon")
require("mrx.plugins.comments")
require("mrx.plugins.cmp")
require("mrx.plugins.lsp.mason")
require("mrx.plugins.lsp.lspconfig")
require("mrx.plugins.lsp.lspsaga")
require("mrx.plugins.lsp.null-ls")
require("mrx.plugins.toggleterm")
